package com.rocketden.main.dao;

import com.rocketden.main.model.Room;
import org.springframework.data.repository.CrudRepository;

public interface RoomRepository extends CrudRepository<Room, Integer> {

    // Auto generated by CrudRepository
    Room findRoomByRoomId(String roomId);
}
