package com.rocketden.main.dao;

import com.rocketden.main.model.User;

import org.springframework.data.repository.CrudRepository;

public interface UserRepository extends CrudRepository<User, Integer> {

    // Auto generated by CrudRepository
    User findUserByUserId(String userId);
}
