package com.rocketden.main.dto.user;

import lombok.EqualsAndHashCode;
import lombok.Getter;
import lombok.Setter;

@Getter
@Setter
@EqualsAndHashCode
public class UserDto {
    private String userId;
    private String nickname;

    // The session ID of the user connection, auto-generated by sockets.
    private String sessionId;
}
