package com.codejoust.main.dao;

import com.codejoust.main.model.Room;

import org.springframework.data.repository.CrudRepository;

public interface RoomRepository extends CrudRepository<Room, Integer> {

    // Auto generated by CrudRepository
    Room findRoomByRoomId(String roomId);
}
