package com.codejoust.main.dao;

import com.codejoust.main.model.User;

import org.springframework.data.repository.CrudRepository;

public interface UserRepository extends CrudRepository<User, Integer> {

    // Auto generated by CrudRepository
    User findUserByUserId(String userId);
    User findUserBySessionId(String sessionId);
}
