import styled from 'styled-components';

export const FlexContainer = styled.div`
  display: flex;
  flex: auto;
  flex-direction: column;
  margin: 1rem;
`;

export const FlexHorizontalContainer = styled.div`
  display: flex;
  flex: auto;
  margin: 1rem;
`;

export const FlexInfoBar = styled.div`
  padding: 0.5rem;
  text-align: center;
  display: flex;
`;

export const FlexLeft = styled.div`
  flex: 1;
  display: flex;
  justify-content: flex-start;
  align-items: center;
`;

export const FlexCenter = styled.div`
  flex: 1;
  display: flex;
  justify-content: center;
  align-items: center;
`;

export const FlexRight = styled.div`
  flex: 1;
  display: flex;
  justify-content: flex-end;
  align-items: center;
`;

export const Panel = styled.div`
  height: 100%;
  padding: 1rem;
  box-sizing: border-box;
  border: 2px solid ${({ theme }) => theme.colors.border};
  border-radius: 10px;
  background-color: white;
`;

export const SplitterContainer = styled.div`
  flex: auto;
  position: relative;
  
  /* References the layout pane class generated by the Monaco Editor. */
  .layout-pane {
    height: 100%;
  }
  
  /* References the layout splitter class generated by the Splitter Layout. */
  .layout-splitter {
    background-color: transparent !important;
  }
`;

export const MainContainer = styled.div`
  margin: 0 auto;
  padding: 5vw 0;
  width: 80%;
`;

export const CenteredContainer = styled.div`
  text-align: center;
  justify-content: center;
`;

export const LandingPageContainer = styled.div`
  position: relative;
  margin: 0 auto;
  width: 66.666%;
  min-width: 450px;
`;
