import styled from 'styled-components';

export const FlexContainer = styled.div`
  display: flex;
  flex: auto;
  flex-direction: column;
  margin: 1rem;
`;

export const FlexHorizontalContainer = styled.div`
  display: flex;
  flex: auto;
  margin: 1rem;
`;

export const FlexInfoBar = styled.div`
  padding: 0.5rem;
  text-align: center;
  display: flex;
`;

export const FlexLeft = styled.div`
  flex: 1;
  display: flex;
  justify-content: flex-start;
  align-items: center;
`;

export const FlexCenter = styled.div`
  flex: 1;
  display: flex;
  justify-content: center;
  align-items: center;
`;

export const FlexRight = styled.div`
  flex: 1;
  display: flex;
  justify-content: flex-end;
  align-items: center;
`;

export const Panel = styled.div`
  height: 100%;
  padding: 1rem;
  box-sizing: border-box;
  border: 2px solid ${({ theme }) => theme.colors.border};
  border-radius: 10px;
  background-color: white;
`;

export const SplitterContainer = styled.div`
  flex: auto;
  position: relative;
  margin: 20px;
  
  .splitter-layout {
    overflow: visible;
  }
  
  /* References the layout pane class generated by the Monaco Editor. */
  .layout-pane {
    height: 100%;
    box-shadow: 0 -1px 5px rgba(0, 0, 0, 0.24);
    border-radius: 5px !important;
    //padding: 5px;
    
    div {
      border: none;
      border-radius: 0;
    }
  }
  
  .layout-pane:nth-of-type(3) {
    box-shadow: none !important;
  }
  
  /* References the layout splitter class generated by the Splitter Layout. */
  .layout-splitter {
    background-color: transparent !important;
    min-width: 20px;
    min-height: 20px;
  }
  
  //.display-box-shadow {
  //  box-shadow: 0 -1px 4px rgba(0, 0, 0, 0.12);
  //  border: 5px transparent solid;
  //  border-radius: 5px !important;
  //}
  
  /* Layout pane that contains nested panes, so do not show the shadow here */
  //.no-box-shadow {
  //  .layout-pane:first-child & {
  //    box-shadow: none;
  //    overflow: visible;
  //  }
  //}
`;

export const MainContainer = styled.div`
  margin: 0 auto;
  padding: 5vw 0;
  width: 80%;
`;

export const CenteredContainer = styled.div`
  text-align: center;
  justify-content: center;
`;

export const LandingPageContainer = styled.div`
  position: relative;
  margin: 0 auto;
  width: 66.666%;

  @media(max-width: 640px) {
    width: 100%;
  }
`;
