package com.rocketden.main.controller;

import com.rocketden.main.dto.problem.Problem;
import com.rocketden.main.dao.problem.ProblemRepository;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.ResponseBody;
import org.springframework.web.bind.annotation.RestController;

@RestController	// This means that this class is a Controller
public class MainController {
	@Autowired // This means to get the bean called userRepository
			   // Which is auto-generated by Spring, we will use it to handle the data
	private ProblemRepository problemRepository;

	@PostMapping("/add")
	public @ResponseBody String addNewProblem (@RequestParam String name
			, @RequestParam String email) {
		// @ResponseBody means the returned String is the response, not a view name
		// @RequestParam means it is a parameter from the GET or POST request

		Problem problem = new Problem();
		problem.setName(name);
		problem.setEmail(email);
    problemRepository.save(problem);
    
    // TODO: return the problem that was saved.
		return "Saved";
	}

	@GetMapping("/all")
	public @ResponseBody Iterable<Problem> getAllProblems() {
		// This returns a JSON with the problems
		return problemRepository.findAll();
	}
}
