package com.rocketden.main.model;

import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;

import lombok.EqualsAndHashCode;
import lombok.Getter;
import lombok.Setter;

@EqualsAndHashCode
@Entity
@Getter
@Setter
public class User {

    // ID used for the database.
    @Id
    @GeneratedValue(strategy = GenerationType.AUTO)
    @EqualsAndHashCode.Exclude
    private Integer id;

    // User ID for user identification and accessible from frontend.
    @GeneratedValue(strategy = GenerationType.AUTO)
    private Integer userId;
    
    private String nickname;

    // The session ID of the user connection, auto-generated by sockets.
    private String sessionId;

    // The status of the user, confirming whether they are online or offline.
    private boolean connected;
}
